### ISSUE TITLE
Different drive letters

### ISSUE THREAD

**Issue by Valzy777** [pkshetlie/RagnaCustomsApp#11]
Guessing this doesn't support if you have steam installed on a different letter than C: ?

System.IO.IOException: Source and destination path must have identical roots. Move will not work across volumes.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at RagnaCustoms.Models.SongProvider.<>c__DisplayClass11_0.<DownloadAsync>g__Client_DownloadFileCompleted|1(Object sender, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Net.WebClient.<StartAsyncOperation>b__78_4(Object arg)

**Comment by pkshetlie** [comment]
is it still a problem ?

**Comment by MelonCola** [comment]
Yes, I'm getting this exact error.
