### ISSUE TITLE
App occassionally crashes when Twitch requests are running

### ISSUE THREAD

**Issue by Brollyy** [pkshetlie/RagnaCustomsApp#47]
The issue seems random, but it happens from time to time. 
Today I managed to get it on my stream and can share the stack trace from error report:
```
Application: RagnaCustoms.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at RagnaCustoms.App.Views.TwitchBotForm+<>c__DisplayClass30_0.<RemoveAtSongRequestInList>b__0(RagnaCustoms.Models.Song)
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Find(System.Predicate`1<System.__Canon>)
   at RagnaCustoms.App.Views.TwitchBotForm.RemoveAtSongRequestInList(System.String)
   at RagnaCustoms.App.Views.TwitchBotForm.OnFileChange(System.Object, System.IO.FileSystemEventArgs)
   at RagnaCustoms.App.Services.FileChangeEvent+<>c__DisplayClass3_0.<OnChange>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by pkshetlie** [comment]
we tried a fix in 2.9.0
