### ISSUE TITLE
App crashes when Twitch form is being opened

### ISSUE THREAD

**Issue by Brollyy** [pkshetlie/RagnaCustomsApp#50]
The cause of the crashes is the missing `Ragnarock.log` file - tracking changes in this file is not strictly necessary for the Twitch requests to run in the first place.

Stack trace:
```Application: RagnaCustoms.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.FileSystemWatcher..ctor(System.String, System.String)
   at RagnaCustoms.App.Services.FileChangeEvent+<>c__DisplayClass1_0.<.ctor>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by pkshetlie** [comment]
some logs are added to the last version (2.9.0) to try to get more informations
